### ISSUE TITLE
AttributeError: 'AsyncioSelectorReactor' object has no attribute '_handleSignals'

### ISSUE THREAD

**Issue by shengchenyang** [shengchenyang/AyugeSpiderTools#10]
**Describe the bug**
在全新环境下安装本库，在程序执行时可能会遇到 `AttributeError: 'AsyncioSelectorReactor' object has no attribute '_handleSignals'` 类似的报错信息。经排查，是 `twisted` 版本更新到 `23.8.0` 后不兼容导致，相关链接：https://docs.scrapy.org/en/latest/news.html#scrapy-2-10-1-2023-08-30

**Versions (please complete the following information):**
 - Device & OS: Linux VM-8-4-centos 3.10.0-1160.81.1.el7.x86_64
 - Version: ayugespidertools-3.4.0
 - Python: Python 3.8.5

**To Reproduce**
1. 创建一个新的 `python` 环境。
2. 安装 `ayugespidertools-3.4.0`。
3. 运行任意一个 `spider` 脚本就会出现此问题。

**Expected behavior**
可以正常运行不报错。

**Screenshots**
无。

**Additional context**
报错详细内容示例如下（本脚本来源为案例 [DemoSpider](https://github.com/shengchenyang/DemoSpider)）：
```
Traceback (most recent call last):
  File "/root/.pyenv/versions/DemoSpider/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/root/.pyenv/versions/DemoSpider/lib/python3.8/site-packages/scrapy/cmdline.py", line 161, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/root/.pyenv/versions/DemoSpider/lib/python3.8/site-packages/scrapy/cmdline.py", line 114, in _run_print_help
    func(*a, **kw)
  File "/root/.pyenv/versions/DemoSpider/lib/python3.8/site-packages/scrapy/cmdline.py", line 169, in _run_command
    cmd.run(args, opts)
  File "/root/.pyenv/versions/DemoSpider/lib/python3.8/site-packages/scrapy/commands/crawl.py", line 30, in run
    self.crawler_process.start()
  File "/root/.pyenv/versions/DemoSpider/lib/python3.8/site-packages/scrapy/crawler.py", line 390, in start
    install_shutdown_handlers(self._signal_shutdown)
  File "/root/.pyenv/versions/DemoSpider/lib/python3.8/site-packages/scrapy/utils/ossignal.py", line 19, in install_shutdown_handlers
    reactor._handleSignals()
AttributeError: 'AsyncioSelectorReactor' object has no attribute '_handleSignals
```

**Comment by shengchenyang** [comment]
最新 `3.4.1` 版本已解决此依赖（兼容）问题，[点击查看对应 release 页面](https://github.com/shengchenyang/AyugeSpiderTools/releases/tag/ayugespidertools-3.4.1)。
