### ISSUE TITLE
安装后运行报错：ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by suyin-long** [shengchenyang/AyugeSpiderTools#9]
**Describe the bug**
安装后运行 `ayuge version` 报错：`ModuleNotFoundError: No module named 'yaml'`
**To Reproduce**
1. 安装 ayugespidertools
2. 运行 `ayuge version`

**Expected behavior**
运行正常

**Screenshots**

**Desktop (please complete the following information):**
- Python：3.10.10
- Windows 11
- ayugespidertools==3.3.2

**Smartphone (please complete the following information):**

**Additional context**
报错代码：
```
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\spider\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\anaconda3\envs\spider\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\anaconda3\envs\spider\Scripts\ayuge.exe\__main__.py", line 4, in <module>
  File "D:\ProgramData\anaconda3\envs\spider\lib\site-packages\ayugespidertools\__init__.py", line 4, in <module>
    from ayugespidertools.scraper.spiders import AyuSpider
  File "D:\ProgramData\anaconda3\envs\spider\lib\site-packages\ayugespidertools\scraper\spiders\__init__.py", line 8, in <module>
    from ayugespidertools.common.spiderconf import (
  File "D:\ProgramData\anaconda3\envs\spider\lib\site-packages\ayugespidertools\common\spiderconf.py", line 14, in <module>
    from ayugespidertools.common.utils import ToolsForAyu
  File "D:\ProgramData\anaconda3\envs\spider\lib\site-packages\ayugespidertools\common\utils.py", line 14, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by shengchenyang** [comment]
报错原因：整理 `poetry` 依赖关系时影响了 `pyyaml` 并导致其丢失，进而安装后缺少使用此库来解析 `consul` 中 `yaml` 格式数据部分时出错。测试及发布流程中未检测出此处错误，是因为我并没有每次新建虚拟环境来测试，导致重新安装本库时未覆盖此场景，属于疏忽导致。

解决方法：可先手动安装依赖，命令为 `pip install PyYAML`，我会尽快修复这个依赖问题并重新发个 `patch` 包。

如果还有疑问，请继续提问，感谢对本项目的关注。

**Comment by shengchenyang** [comment]
已修复此问题，并发布了 `3.3.3` 版本，[点击可跳转至对应 release 页面](https://github.com/shengchenyang/AyugeSpiderTools/releases/ayugespidertools-3.3.3)。

你可以输入 `pip install -U ayugespidertools -i https://pypi.org/simple` 命令升级即可。
如无问题，我会在一段时间后关闭此 `issue`，若还未解决你的问题，可随时激活此页面。再次感谢你的反馈。

**Comment by suyin-long** [comment]
改用 3.3.3 版本后确实可以正常使用了。
提个问题，为啥要安装要用 `pip install ayugespidertools -i https://pypi.org/simple`  这个命令？使用这条命令安装速度太慢了（20kb/s），安装了一上午没有安装完，后来改为使用 `pip install ayugespidertools` 命令安装，不用1分钟安装完毕（8mb/s ），只需要配置一个 pip 源即可！

**Comment by shengchenyang** [comment]
因为 `https://pypi.org/simple` 是 `pypi` 官方源地址，所以是需要科学访问的。安装示例加上它是因为官方源发布后即刻生效，但国内各种源可能会对第三方库的收录（同步）速度不是非常快的。其实影响不大，以防万一而已。

**Comment by suyin-long** [comment]
> 因为 `https://pypi.org/simple` 是 `pypi` 官方源地址，所以是需要科学访问的。安装示例加上它是因为官方源发布后即刻生效，但国内各种源可能会对第三方库的收录（同步）速度不是非常快的。其实影响不大，以防万一而已。

好的，明白了

**Comment by suyin-long** [comment]
大佬，有交流群吗？

**Comment by shengchenyang** [comment]
没有，我也不太想给此项目添加 `Discussions` 功能或者是讨论群之类的。若觉得一些交流内容会"污染" `issue` 板块，可直接到我的[个人主页](https://github.com/shengchenyang)中与我邮件交流。
